In [4]:
import pandas as pd
from matplotlib import pyplot as plt
from sklearn import datasets
import sklearn.datasets as datasets
from sklearn.model_selection import train_test_split
# from sklearn.metrics import classification_report, plot_confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
import seaborn as sns

In [7]:
import os

In [5]:
from google.colab import drive   # 코랩 드라이브와 연동
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


### loading dataset

In [8]:
data_path = '/content/drive/MyDrive/gachon4-2/deeplearning/week2/Pumpkin_Seeds_Dataset'

In [9]:
df = pd.DataFrame(pd.read_excel(os.path.join(data_path,"Pumpkin_Seeds_Dataset.xlsx")))

In [11]:
df.head()

Area  Perimeter  Major_Axis_Length  Minor_Axis_Length  Convex_Area  \
0  56276    888.242           326.1485           220.2388        56831   
1  76631   1068.146           417.1932           234.2289        77280   
2  71623   1082.987           435.8328           211.0457        72663   
3  66458    992.051           381.5638           222.5322        67118   
4  66107    998.146           383.8883           220.4545        67117   

   Equiv_Diameter  Eccentricity  Solidity  Extent  Roundness  Aspect_Ration  \
0        267.6805        0.7376    0.9902  0.7453     0.8963         1.4809   
1        312.3614        0.8275    0.9916  0.7151     0.8440         1.7811   
2        301.9822        0.8749    0.9857  0.7400     0.7674         2.0651   
3        290.8899        0.8123    0.9902  0.7396     0.8486         1.7146   
4        290.1207        0.8187    0.9850  0.6752     0.8338         1.7413   

   Compactness       Class  
0       0.8207  Çerçevelik  
1       0.7487  Çerçevelik  
2       0.6929  Çerçevelik  
3       0.7624  Çerçevelik  
4       0.7557  Çerçevelik

In [12]:
df.isnull().any()

Area                 False
Perimeter            False
Major_Axis_Length    False
Minor_Axis_Length    False
Convex_Area          False
Equiv_Diameter       False
Eccentricity         False
Solidity             False
Extent               False
Roundness            False
Aspect_Ration        False
Compactness          False
Class                False
dtype: bool

In [13]:
df.dtypes

Area                   int64
Perimeter            float64
Major_Axis_Length    float64
Minor_Axis_Length    float64
Convex_Area            int64
Equiv_Diameter       float64
Eccentricity         float64
Solidity             float64
Extent               float64
Roundness            float64
Aspect_Ration        float64
Compactness          float64
Class                 object
dtype: object

In [15]:
df.keys()

Index(['Area', 'Perimeter', 'Major_Axis_Length', 'Minor_Axis_Length',
       'Convex_Area', 'Equiv_Diameter', 'Eccentricity', 'Solidity', 'Extent',
       'Roundness', 'Aspect_Ration', 'Compactness', 'Class'],
      dtype='object')

In [18]:
X = df[['Area', 'Perimeter', 'Major_Axis_Length', 'Minor_Axis_Length',
       'Convex_Area', 'Equiv_Diameter', 'Eccentricity', 'Solidity', 'Extent',
       'Roundness', 'Aspect_Ration', 'Compactness']].values
Y = df['Class'].values

In [42]:
import numpy as np
print("lable class : ", np.unique(Y))

lable class :  ['Çerçevelik' 'Ürgüp Sivrisi']


In [17]:
print(X[:3])
print(Y[:3])

[[5.627600e+04 8.882420e+02 3.261485e+02 2.202388e+02 5.683100e+04
  2.676805e+02 7.376000e-01 9.902000e-01 7.453000e-01 8.963000e-01
  1.480900e+00 8.207000e-01]
 [7.663100e+04 1.068146e+03 4.171932e+02 2.342289e+02 7.728000e+04
  3.123614e+02 8.275000e-01 9.916000e-01 7.151000e-01 8.440000e-01
  1.781100e+00 7.487000e-01]
 [7.162300e+04 1.082987e+03 4.358328e+02 2.110457e+02 7.266300e+04
  3.019822e+02 8.749000e-01 9.857000e-01 7.400000e-01 7.674000e-01
  2.065100e+00 6.929000e-01]]
['Çerçevelik' 'Çerçevelik' 'Çerçevelik']


In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.9, random_state=1)

In [21]:
print(len(X_train),len(Y_train))
print(len(X_test), len(Y_test))

2250 2250
250 250


### 1) "Decision Tree" model

In [44]:
# 1. train the decision tree classifier
#scikit learn decision tree model training
DT = tree.DecisionTreeClassifier()
DT = DT.fit(X_train, Y_train)

# 2. test the model trained on test set
DT.predict(X_test)
prediction = DT.predict(X_test)

# 3. perform evaluation on test set
import sklearn.metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
# evaluation for multi class classification
print(classification_report(Y_test, prediction))
print('Accuracy Score:', metrics.accuracy_score(Y_test, prediction))

cm = confusion_matrix(Y_test, prediction)
print(cm)

               precision    recall  f1-score   support

   Çerçevelik       0.84      0.84      0.84       133
Ürgüp Sivrisi       0.82      0.82      0.82       117

     accuracy                           0.83       250
    macro avg       0.83      0.83      0.83       250
 weighted avg       0.83      0.83      0.83       250

Accuracy Score: 0.832
[[112  21]
 [ 21  96]]


### 2) "LogisticRegression" model

In [45]:
from sklearn.linear_model import LogisticRegression

# 1. train the LogisticRegression classifier
clf = LogisticRegression()
clf = clf.fit(X_train, Y_train)

# 2. test the model trained on test set
clf.predict(X_test)
prediction = clf.predict(X_test)

# 3. perform evaluation on test set
import sklearn.metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
# evaluation for multi class classification
print(classification_report(Y_test, prediction))
print('Accuracy Score:', metrics.accuracy_score(Y_test, prediction))

cm = confusion_matrix(Y_test, prediction)
print(cm)

               precision    recall  f1-score   support

   Çerçevelik       0.87      0.88      0.88       133
Ürgüp Sivrisi       0.86      0.85      0.86       117

     accuracy                           0.87       250
    macro avg       0.87      0.87      0.87       250
 weighted avg       0.87      0.87      0.87       250

Accuracy Score: 0.868
[[117  16]
 [ 17 100]]


### 3) "RandomForestClassifier" model

In [46]:
from sklearn.ensemble import RandomForestClassifier

# 1. train the LogisticRegression classifier
clf = RandomForestClassifier(max_depth=10, random_state=0)
clf = clf.fit(X_train, Y_train)

# 2. test the model trained on test set
clf.predict(X_test)
prediction = clf.predict(X_test)

# 3. perform evaluation on test set
import sklearn.metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
# evaluation for multi class classification
print(classification_report(Y_test, prediction))
print('Accuracy Score:', metrics.accuracy_score(Y_test, prediction))

cm = confusion_matrix(Y_test, prediction)
print(cm)

               precision    recall  f1-score   support

   Çerçevelik       0.89      0.91      0.90       133
Ürgüp Sivrisi       0.89      0.87      0.88       117

     accuracy                           0.89       250
    macro avg       0.89      0.89      0.89       250
 weighted avg       0.89      0.89      0.89       250

Accuracy Score: 0.892
[[121  12]
 [ 15 102]]


### 4) "SVM" model

In [49]:
from sklearn.pipeline import make_pipeline
>>> from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))
clf = clf.fit(X_train, Y_train)

# 2. test the model trained on test set
clf.predict(X_test)
prediction = clf.predict(X_test)

# 3. perform evaluation on test set
import sklearn.metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
# evaluation for multi class classification
print(classification_report(Y_test, prediction))
print('Accuracy Score:', metrics.accuracy_score(Y_test, prediction))

cm = confusion_matrix(Y_test, prediction)
print(cm)

               precision    recall  f1-score   support

   Çerçevelik       0.88      0.92      0.90       133
Ürgüp Sivrisi       0.90      0.85      0.88       117

     accuracy                           0.89       250
    macro avg       0.89      0.89      0.89       250
 weighted avg       0.89      0.89      0.89       250

Accuracy Score: 0.888
[[122  11]
 [ 17 100]]
