In [29]:
import pandas as pd
from matplotlib import pyplot as plt
from sklearn import datasets
import sklearn.datasets as datasets
from sklearn.model_selection import train_test_split
# from sklearn.metrics import classification_report, plot_confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
import seaborn as sns

In [30]:
import os

In [31]:
from google.colab import drive   # 코랩 드라이브와 연동
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


### loading dataset

In [32]:
data_path = '/content/drive/MyDrive/gachon4-2/deeplearning/week2/car+evaluation'

In [33]:
df = pd.DataFrame(pd.read_csv(os.path.join(data_path,"car_evaluation.csv")))

In [34]:
df.head()

vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1727 entries, 0 to 1726
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   vhigh    1727 non-null   object
 1   vhigh.1  1727 non-null   object
 2   2        1727 non-null   object
 3   2.1      1727 non-null   object
 4   small    1727 non-null   object
 5   low      1727 non-null   object
 6   unacc    1727 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [53]:
print("vhigh value: ",np.unique(df['vhigh'].values))
print("vhigh.1 value: ",np.unique(df['vhigh.1'].values))
print("2 value: ",np.unique(df['2'].values))
print("2.1 value: ",np.unique(df['2.1'].values))
print("small value: ",np.unique(df['small'].values))
print("low value: ",np.unique(df['low'].values))
print("label class: ",np.unique(df['unacc'].values))

vhigh value:  ['high' 'low' 'med' 'vhigh']
vhigh.1 value:  ['high' 'low' 'med' 'vhigh']
2 value:  ['2' '3' '4' '5more']
2.1 value:  ['2' '4' 'more']
small value:  ['big' 'med' 'small']
low value:  ['high' 'low' 'med']
label class:  ['acc' 'good' 'unacc' 'vgood']


In [54]:
df.keys()

Index(['vhigh', 'vhigh.1', '2', '2.1', 'small', 'low', 'unacc'], dtype='object')

In [55]:
X = df[['vhigh', 'vhigh.1', '2', '2.1', 'small', 'low']]
Y = df['unacc']

In [56]:
print(X[:3])
print(Y[:3])

   vhigh vhigh.1  2 2.1  small   low
0  vhigh   vhigh  2   2  small   med
1  vhigh   vhigh  2   2  small  high
2  vhigh   vhigh  2   2    med   low
0    unacc
1    unacc
2    unacc
Name: unacc, dtype: object


In [57]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.9, random_state=1, shuffle=True)

In [58]:
print(len(X_train),len(Y_train))
print(len(X_test), len(Y_test))

1554 1554
173 173


In [59]:
X_train.shape

(1554, 6)

In [60]:
import category_encoders as ce

encoder = ce.OrdinalEncoder(cols=['vhigh', 'vhigh.1', '2', '2.1', 'small', 'low'])
X_train = encoder.fit_transform(X_train)
X_test = encoder.transform(X_test)


In [63]:
print("vhigh value: ",np.unique(X_train['vhigh'].values))
print("vhigh.1 value: ",np.unique(X_train['vhigh.1'].values))
print("2 value: ",np.unique(X_train['2'].values))
print("2.1 value: ",np.unique(X_train['2.1'].values))
print("small value: ",np.unique(X_train['small'].values))
print("low value: ",np.unique(X_train['low'].values))

vhigh value:  [1 2 3 4]
vhigh.1 value:  [1 2 3 4]
2 value:  [1 2 3 4]
2.1 value:  [1 2 3]
small value:  [1 2 3]
low value:  [1 2 3]


### 1) "Decision Tree" model

In [64]:
# 1. train the decision tree classifier
#scikit learn decision tree model training
DT = tree.DecisionTreeClassifier()
DT = DT.fit(X_train, Y_train)

# 2. test the model trained on test set
DT.predict(X_test)
prediction = DT.predict(X_test)

# 3. perform evaluation on test set
import sklearn.metrics as metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
# evaluation for multi class classification
print(classification_report(Y_test, prediction))
print('Accuracy Score:', metrics.accuracy_score(Y_test, prediction))

cm = confusion_matrix(Y_test, prediction)
print(cm)

              precision    recall  f1-score   support

         acc       0.86      1.00      0.92        30
        good       1.00      1.00      1.00         6
       unacc       1.00      0.97      0.98       127
       vgood       1.00      0.90      0.95        10

    accuracy                           0.97       173
   macro avg       0.96      0.97      0.96       173
weighted avg       0.98      0.97      0.97       173

Accuracy Score: 0.9710982658959537
[[ 30   0   0   0]
 [  0   6   0   0]
 [  4   0 123   0]
 [  1   0   0   9]]


### 2) "LogisticRegression" model

In [65]:
from sklearn.linear_model import LogisticRegression

# 1. train the LogisticRegression classifier
clf = LogisticRegression()
clf = clf.fit(X_train, Y_train)

# 2. test the model trained on test set
clf.predict(X_test)
prediction = clf.predict(X_test)

# 3. perform evaluation on test set
import sklearn.metrics as metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
# evaluation for multi class classification
print(classification_report(Y_test, prediction))
print('Accuracy Score:', metrics.accuracy_score(Y_test, prediction))

cm = confusion_matrix(Y_test, prediction)
print(cm)

              precision    recall  f1-score   support

         acc       0.33      0.30      0.32        30
        good       0.00      0.00      0.00         6
       unacc       0.82      0.91      0.86       127
       vgood       1.00      0.40      0.57        10

    accuracy                           0.74       173
   macro avg       0.54      0.40      0.44       173
weighted avg       0.72      0.74      0.72       173

Accuracy Score: 0.7398843930635838
[[  9   0  21   0]
 [  4   0   2   0]
 [ 10   2 115   0]
 [  4   0   2   4]]


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


### 3) "RandomForestClassifier" model

In [66]:
from sklearn.ensemble import RandomForestClassifier

# 1. train the LogisticRegression classifier
clf = RandomForestClassifier(max_depth=10, random_state=0)
clf = clf.fit(X_train, Y_train)

# 2. test the model trained on test set
clf.predict(X_test)
prediction = clf.predict(X_test)

# 3. perform evaluation on test set
import sklearn.metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
# evaluation for multi class classification
print(classification_report(Y_test, prediction))
print('Accuracy Score:', metrics.accuracy_score(Y_test, prediction))

cm = confusion_matrix(Y_test, prediction)
print(cm)

              precision    recall  f1-score   support

         acc       0.85      0.97      0.91        30
        good       1.00      0.83      0.91         6
       unacc       0.99      0.98      0.98       127
       vgood       1.00      0.90      0.95        10

    accuracy                           0.97       173
   macro avg       0.96      0.92      0.94       173
weighted avg       0.97      0.97      0.97       173

Accuracy Score: 0.9653179190751445
[[ 29   0   1   0]
 [  1   5   0   0]
 [  3   0 124   0]
 [  1   0   0   9]]


### 4) "SVM" model

In [67]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
clf = make_pipeline(StandardScaler(), SVC(gamma='auto'))
clf = clf.fit(X_train, Y_train)

# 2. test the model trained on test set
clf.predict(X_test)
prediction = clf.predict(X_test)

# 3. perform evaluation on test set
import sklearn.metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
# evaluation for multi class classification
print(classification_report(Y_test, prediction))
print('Accuracy Score:', metrics.accuracy_score(Y_test, prediction))

cm = confusion_matrix(Y_test, prediction)
print(cm)

              precision    recall  f1-score   support

         acc       0.63      0.90      0.74        30
        good       0.00      0.00      0.00         6
       unacc       0.98      0.95      0.96       127
       vgood       1.00      0.60      0.75        10

    accuracy                           0.89       173
   macro avg       0.65      0.61      0.61       173
weighted avg       0.88      0.89      0.88       173

Accuracy Score: 0.8901734104046243
[[ 27   0   3   0]
 [  6   0   0   0]
 [  6   0 121   0]
 [  4   0   0   6]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
